### ISSUE TITLE
GameEngine runs init() twice upon startup

### ISSUE THREAD

**Issue by tinovasq** [CremBluRay/voodoo2d#14]
**Describe the bug**
GameEngine runs init() twice upon startup: not a 'game breaking' bug per se (ha), but does interfere with the map tileset parsing and construction, which is how I found it.

**To Reproduce**
1. Navigate to `src/main/.../voodoo2d/engine/GameEngine.java`.
2. Using either IDE breakpoints or a println(), mark the method call of init().
3. notice the double run logic error.

**Expected behavior**
The method should be called once, as it is an initialization.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win10 Home 64bit
 - Browser: N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
None.

**Comment by JacksonHoggard** [comment]
I followed the steps to reproduce and I don't seem to be having this issue. Could it be an issue caused by some code you added? Here are some screenshots with the code I ran trying to reproduce the error:
![image](https://user-images.githubusercontent.com/22283001/84617755-8ef4f600-ae95-11ea-9cdc-23ef9fe827bc.png)
![image](https://user-images.githubusercontent.com/22283001/84617785-a7fda700-ae95-11ea-9150-8c4c95493b6b.png)

**Comment by tinovasq** [comment]
Thanks, used this to figure out the issue. My install did something odd, when I recompiled it is working fine.

**Comment by JacksonHoggard** [comment]
No problem! Glad you could resolve the issue!
